pipeline:
  name: Python App
  identifier: Python_App
  projectIdentifier: testravimetta
  orgIdentifier: TPMLabs
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: ravigitconnector
        repoName: harness-python-pipeline-sample
        build: <+input>
  stages:
    - stage:
        name: Build App
        identifier: Build_App
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Code Compile
                  identifier: Code_Compile
                  spec:
                    connectorRef: ravidockerconnector
                    image: python:3.10.6-alpine
                    shell: Sh
                    command: pip install -r requirements.txt
              - parallel:
                  - step:
                      type: Bandit
                      name: Security Scan
                      identifier: Security_Scan
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: repository
                          detection: auto
                        advanced:
                          log:
                            level: info
                  - step:
                      type: BuildAndPushDockerRegistry
                      name: BuildAndPushDockerRegistry_1
                      identifier: BuildAndPushDockerRegistry_1
                      spec:
                        connectorRef: ravidockerconnector
                        repo: rmettadocker/pythonapp
                        tags:
                          - <+codebase.commitSha>
                          - latest
                        caching: true
    - stage:
        name: integration test
        identifier: integration_test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
            paths: []
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Background
                  name: python server
                  identifier: python_server
                  spec:
                    connectorRef: ravidockerconnector
                    image: python-pipeline-samples
                    shell: Sh
                    command: python3 /python-pipeline-samples/app.py
                  description: server connection
              - step:
                  type: Run
                  name: Connection Test
                  identifier: Connection_Test
                  spec:
                    connectorRef: ravidockerconnector
                    image: curlimages/curl:7.73.0
                    shell: Sh
                    command: |-
                      sleep 10
                      curl localhost:5000
