pipeline:
  name: ravi-build-python-pipeline-sample
  identifier: Build_ravimtestgit_harness_python_pipeline_sample_1723398046883
  projectIdentifier: raviexercise
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
              - step:
                  type: Run
                  name: Compile Code Step
                  identifier: Compile_Code_Step
                  spec:
                    connectorRef: account.DockerHubAccess
                    image: python:3.10.6-alpine
                    shell: Sh
                    command: python -m compileall ./
              - step:
                  type: Run
                  name: create docker file
                  identifier: create_docker_file
                  spec:
                    connectorRef: account.DockerHubAccess
                    image: alpine
                    shell: Sh
                    command: |-
                      touch pythondockerfile
                      cat > pythondockerfile <<- EOM
                      FROM python:3.10.6-alpine
                      WORKDIR /python-pipeline-samples
                      ADD . /python-pipeline-samples
                      RUN pip install -r requirements.txt
                      CMD ["python" , "app.py"]
                      EOM
                      cat pythondockerfile
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.DockerHubAccess
                    repo: ravimdocker/ravi-exercise
                    tags:
                      - ravi1
                    dockerfile: pythondockerfile
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        description: ""
    - stage:
        name: Run Tests
        identifier: Run_Tests
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          caching:
            enabled: false
            paths: []
          execution:
            steps:
              - step:
                  type: Background
                  name: python server
                  identifier: python_server
                  spec:
                    connectorRef: account.DockerHubAccess
                    image: ravimdocker/ravi-exercise
                    shell: Sh
                    command: python3 /python-pipeline-samples/app.py
              - step:
                  type: Run
                  name: test connection to server
                  identifier: test_connection_to_server
                  spec:
                    connectorRef: account.DockerHubAccess
                    image: curlimages/curl:7.73.0
                    shell: Sh
                    command: |-
                      sleep 10
                      curl localhost:5000
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1723388863815
        repoName: ravimtestgit/harness-python-pipeline-sample
        build: <+input>
